name: GitHub actions kustomize argocd manifests
author: Gabriel Ferreira <gabriel.oliveira@platformbuilders.io>
description: GitHub action used to get git repository informations
branding:
  icon: feather
  color: gray-dark

inputs:
  gitops-repo-name:
    description: 'The name of GitOps repository'
    required: true
  gitops-repo-url:
    description: 'The URL of GitOps repository'
    required: true
  GH_ACCESS_TOKEN:
    description: 'The access token of GitOps repository'
    required: true
  GCP_PROJECT_ID_PROD:
    description: 'The GCP project ID'
    required: true
  APP_ID:
    description: 'The App ID'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.gitops-repo-name }}
    - ${{ inputs.gitops-repo-url }}
    - ${{ inputs.GH_ACCESS_TOKEN }}
    - ${{ inputs.GCP_PROJECT_ID_PROD }}
    - ${{ inputs.APP_ID }}